### ISSUE TITLE
Release Notification

### ISSUE THREAD

**Issue by bquistorff** [bquistorff/synth_runner#1]
This issue is solely to trigger email notification when a new release is published. I'll leave a comment here when new versions are available. Please do not post bugs here! Use new issues for those.

NB: See [here](http://stackoverflow.com/questions/20839622/) for other methods of tracking project releases.

**Comment by bquistorff** [comment]
Released v1.1.5. See the Changelog for details.

**Comment by bquistorff** [comment]
Released v.1.2.0.

**Comment by flowercong** [comment]
Hi Brian,

Thank you for writing the package. I am using it for my dissertation work.  Just ran into a problem with using the "single_treatment_graphs" syntax. After running the SCM analysis, I had no trouble producing this graph with the following syntax:

effect_graphs, depvar(plowinc) depvar_synth(plowinc_synth) trunit(104179) trperiod(2011) effect_var(effect)

But had issue with this one: 

single_treatment_graphs, depvar(plowinc) trunit(104179) trperiod(2011)
Got this message from STATA "plowinc ambiguous abbreviation
r(111)"

Do you have any idea why there "plowinc" is not a problem for producing the effect_graphs, but becomes an issue for the single_treatment_graphs? 

Thank you,
Huacong

**Comment by bquistorff** [comment]
Hmmm... Do you have another variable that starts with `plowinc`? If so, you could try renaming that. You could also `set trace on` and then `set tracedepth 2` and rerun the command and see what line gives the error. That would help me figure it out (also include a list of variables).

**Comment by bquistorff** [comment]
Released v1.3.0

**Comment by ranand985** [comment]
Hi Brian,

Thank you for writing this package. I was stuck with the "conformability error" while using the 'synth' command. Then I came across your comments on the conformability issues and I downloaded the synth_runner package and made the changes you mentioned.

However, now I am getting the error " Panel must be strongly balanced"
My dataset is weakly balanced and I don't think I can do much about it. Is there any way around this problem?

Thanks,
Rahul

**Comment by bquistorff** [comment]
Released v.1.6.0

**Comment by I-Ulkar** [comment]
Hi Brian, 

I am using this package for one of my papers. Yet, I noticed that as the order of covariates changes, the results change as well. Do you have any idea why this is happening?

**Comment by bquistorff** [comment]
This is an issue with the underlying `synth`. If you have more concerns please open a separate new issue.

**Comment by bquistorff** [comment]
You should be able to see which line this happens on. Be careful when copying from PDFs as this can mangle the quotes. If you still have issues open up a new issue and input the information asked for.

**Comment by bquistorff** [comment]
No longer needed as built into GitHub API [here](https://help.github.com/en/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-releases-for-a-repository).
