### ISSUE TITLE
How to get stata to spit out the average and  standard error around that for each placebo set for each treatment period in synth_runner 

### ISSUE THREAD

**Issue by syedishraque** [bquistorff/synth_runner#11]
<Edit: User did not leave information>

**Comment by bquistorff** [comment]
I do not understand what you are asking for. Please elaborate.

**Comment by syedishraque** [comment]
sorry I should have made it clearer. synth_runner calculates placebo averages for each treatment period. how can I get the  standard deviation of the distribution of the placebo estimates? To be precise how can I get STATA to display the standard error of the placebo effect distribution? I need placebo estimates' average and the standard error for those placebo estimates for my work.

Thanks, Syed

**Comment by bquistorff** [comment]
If you have one treatment period then you can get the placebo outcomes into the dataset (see the gen_vars option in the newest release) and then you can do any calculation you want on them. If there are multiple treatment periods then this your request is currently not possible.
