### ISSUE TITLE
Treatment line offset issue

### ISSUE THREAD

**Issue by vide25** [bquistorff/synth_runner#14]
# Preliminaries
Before submitting an issue, please check (with `x` in brackets) that you:
- [X] Are using the newest release (see [here](https://github.com/bquistorff/synth_runner/releases) for latest release version number).
- [X] Have checked that the examples in the help work.
- [X] Have read the help ([HTML version](https://rawgit.com/bquistorff/synth_runner/master/code/ado/synth_runner.html)).
- [X] Have checked that there is not already an existing issues for what you are reporting.

# Expected behavior and actual behavior
When using the single_treatment_graphs command, the trlinediff() option offsets the treatment line for the effects graph but does not do so for the raw graph. This occurred for the example in the help file, as well as in the data set in which I am working.

# Steps to reproduce the problem

sysuse smoking
tsset state year
synth cigsale beer(1984(1)1988) lnincome(1972(1)1988) retprice age15to24 cigsale(1988) cigsale(1980) cigsale(1975), trunit(3) trperiod(1989) gen_vars
synth_runner cigsale beer(1984(1)1988) lnincome(1972(1)1988) retprice age15to24 cigsale(1988) cigsale(1980) cigsale(1975), trunit(3) trperiod(1989) gen_vars

* The trlinediff(1) option should shift the treatment line +1. 
* This happens in the effects graph, but not in the raw graph
single_treatment_graphs, trlinediff(1) effects_ylabels(-30(10)30) effects_ymax(35) effects_ymin(-35)

# System information

* Stata version and flavor (e.g. v14 MP): v14.2 SE
* OS type and version (e.g. Windows 10): iOS 10.12
* synth_runner version: 1.6.0

**Comment by bquistorff** [comment]
Thanks. Fixed.
