### ISSUE TITLE
synth_runner won't run with missing values

### ISSUE THREAD

**Issue by haiyueji** [bquistorff/synth_runner#15]
We have missing data in several years. The missing data for each covariate occur in the same years for all the states. And we cannot run synth_runner because it constantly tells us it's invalid syntax. Attempting to specify the years for each covariate to exclude their missing data years works for synth, but doesn't work for synth_runner. Attached is our log file. Can you see where went wrong? Thank you!
[599Project.log](https://github.com/bquistorff/synth_runner/files/1484227/599Project.log)

**Comment by bquistorff** [comment]
Can you provide a minimum working example](https://stackoverflow.com/help/mcve) with a built-in dataset?

**Comment by dvmasterov** [comment]
There MWP on this SO post (along with two other problems): https://stackoverflow.com/a/48553073/1187671

**Comment by bquistorff** [comment]
That post has missing outcome data (in which case you might have to drop that year) rather than missing covariate data. The smoking example has missing covariate data and runs fine.

**Comment by bquistorff** [comment]
Closing until we can get reproducible steps for the bug.
