### ISSUE TITLE
nested option in synth

### ISSUE THREAD

**Issue by hwanoong** [bquistorff/synth_runner#16]
Hi Brian,

Thank you very much for providing this package to us. My problem is the optimal weights for the synthetic control group are different from using "synth" and  "synth_runner". 

I guess the reason is synth_runner does not use "nested" option (correct?) as I see pre_rmpse is way much larger than when I use "synth" command.  Can you incorporate"nested" option in your package? 

It would be great if users can have "nested" option as some cases matching pre-trends is poor without this.  

Best,
Hwanoong 
# Preliminaries
Before submitting an issue, please check (with `x` in brackets) that you:
- [x] Are using the newest release (see [here](https://github.com/bquistorff/synth_runner/releases) for latest release version number).
- [x] Have checked that the examples in the help work.
- [x] Have read the help ([HTML version](https://rawgit.com/bquistorff/synth_runner/master/code/ado/synth_runner.html)).
- [x] Have checked that there is not already an existing issues for what you are reporting.
- [x] Have check running synth directly for one of the treated units works.

# Expected behavior and actual behavior
Described what you expected to see and what you actually see

# Steps to reproduce the problem

Please include a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve). If possible, use system-provided or generated data. Otherwise please link to data so that the example can be verified by others. Format the code with an initial and final line of three backticks(`) for readability (see [GitHub's markdown formatting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet))

# System information

* Stata version and flavor (e.g. v14 MP):
* OS type and version (e.g. Windows 10):
* synth_runner version:

**Comment by bquistorff** [comment]
You already can. Just pass in 'nested' and it will get passed on to `synth`.
