### ISSUE TITLE
Dropping treated unit(s) from potential donor set when calculating p-values

### ISSUE THREAD

**Issue by dvmasterov** [bquistorff/synth_runner#19]
In the SJ paper, in the section on inference using in-place placebos, you write "Disallow the actual treated unit from being considered for the synthetic controls of these other units." I am not sure why this is necessary or desirable. I don't believe this is done with permutation tests in general (based on Phillip Good's book), and I don't see this mentioned elsewhere in the SC literature explicitly.

The only place where I see this discussed is http://scunning.com/cunningham_mixtape.pdf on p.275, where the opposite advice is given.

Could you point me to an explanation why synth_runner does this? 

# Preliminaries
Before submitting an issue, please check (with `x` in brackets) that you:
- [ ] Are using the newest release (see [here](https://github.com/bquistorff/synth_runner/releases) for latest release version number).
- [ ] Have checked that the examples in the help work.
- [ ] Have read the help ([HTML version](https://rawgit.com/bquistorff/synth_runner/master/code/ado/synth_runner.html)).
- [ ] Have checked that there is not already an existing issues for what you are reporting.
- [ ] Have check running synth directly for one of the treated units works.

# Expected behavior and actual behavior
Described what you expected to see and what you actually see

# Steps to reproduce the problem

Please include a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve). If possible, use system-provided or generated data. Otherwise please link to data so that the example can be verified by others. Format the code with an initial and final line of three backticks(`) for readability (see [GitHub's markdown formatting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet))

# System information

* Stata version and flavor (e.g. v14 MP):
* OS type and version (e.g. Windows 10):
* synth_runner version:

**Comment by bquistorff** [comment]
This is what Cavallo et al. (2013) do. Code for including them in the fraction is the first example in the paper.
