### ISSUE TITLE
Problem with example "smoking"

### ISSUE THREAD

**Issue by Liviayi** [bquistorff/synth_runner#20]
# Preliminaries
Before submitting an issue, please check (with `x` in brackets) that you:
- [x] Are using the newest release (see [here](https://github.com/bquistorff/synth_runner/releases) for latest release version number).
- [x] Have checked that the examples in the help work.
- [x] Have read the help ([HTML version](https://rawgit.com/bquistorff/synth_runner/master/code/ado/synth_runner.html)).
- [x] Have checked that there is not already an existing issues for what you are reporting.
- [ ] Have check running synth directly for one of the treated units works.

# Expected behavior and actual behavior
Described what you expected to see and what you actually see

# Steps to reproduce the problem

Please include a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve). If possible, use system-provided or generated data. Otherwise please link to data so that the example can be verified by others. Format the code with an initial and final line of three backticks(`) for readability (see [GitHub's markdown formatting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet))

# System information

* Stata version and flavor (e.g. v14 MP):
* OS type and version (e.g. Windows 10):
* synth_runner version:

**Comment by Liviayi** [comment]
I am using Stata IC 14.2. I have trouble running the examples in the help file. After "sysuse smoking", my smoking file actually look like the following. There is no "state" or "year" variable. Do you have any idea why that is the case?

![capture](https://user-images.githubusercontent.com/39444695/40272631-0079203c-5b76-11e8-8bbe-49548cf0c50c.PNG)

**Comment by bquistorff** [comment]
SSC changed the `smoking.dta` file in `synth`. You can get the original version from my repo [here](https://github.com/bquistorff/synth_runner/raw/master/code/ado/smoking.dta).

**Comment by bquistorff** [comment]
The `synth` package has been updated with the correct dataset and its name is now `synth_smoking`. I've fixed the help and main README.md
