### ISSUE TITLE
synthopt.plugin not found

### ISSUE THREAD

**Issue by yezidher** [bquistorff/synth_runner#23]
# Preliminaries
Before submitting an issue, please check (with `x` in brackets) that you:
- [ ] Are using the newest release (see [here](https://github.com/bquistorff/synth_runner/releases) for latest release version number).
- [ ] Have checked that the examples in the help work.
- [ ] Have read the help ([HTML version](https://rawgit.com/bquistorff/synth_runner/master/code/ado/synth_runner.html)).
- [ ] Have checked that there is not already an existing issues for what you are reporting.
- [ ] Have check running synth directly for one of the treated units works.

# Expected behavior and actual behavior
Described what you expected to see and what you actually see

# Steps to reproduce the problem

Please include a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve). If possible, use system-provided or generated data. Otherwise please link to data so that the example can be verified by others. Format the code with an initial and final line of three backticks(`) for readability (see [GitHub's markdown formatting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet))

# System information

* Stata version and flavor (e.g. v14 MP):
* OS type and version (e.g. Windows 10):
* synth_runner version:

**Comment by yezidher** [comment]
I cannot follow the exemple. The run synth_runner do not work. Please find here the error Stata show me. How can I solve this error, looks like I only need to add the synthopt.plugin to the directory, but I don't know how to do that. Thanks in advance for your help. 

. synth_runner cigsale beer(1984(1)1988) lnincome(1972(1)1988) retprice age15to24 cigsale(1988) cigsale(1980) cigsale(1975), trunit
> (3) trperiod(1989) gen_vars
file synthopt.plugin not found
Estimating the treatment effects
file synthopt.plugin not found
Error estimating treatment effect for unit 3
Re-running last -synth- command with output/errors un-captured
file synthopt.plugin not found
(error occurred while loading synth.ado)
r(601);

**Comment by bquistorff** [comment]
Try to uninstall then re-install from GitHub. See if the plugin was installed with the package by using `which synthopt.plugin` which for me returns `C:\Program Files (x86)\Stata14\ado\plus\s\synthopt.plugin`

**Comment by yezidher** [comment]
Thank you for your answer. I have uninstalled and re-installed the package from GitHub, but still it doesn't work. When I write "which synthopt.plugin" in Stata, the outcome is "file synthopt.plugin not found along the ado-path". Initially I thought it was a problem of Stata 11, but then I tried with Stata 14 and got the same error.

**Comment by bquistorff** [comment]
Sorry, I should've said to uninstall and reinstall `synth` (from SSC) as `synthopt.plugin` is from `synth` not my package. Looks like you need to get `synth` working first. See if you can get their examples to work. You could try looking at your ADOPATH (try `mac dir` to see `S_ADO` and then `sysdir` to see the codeword paths) and see where you are installing packages (`net query`) then actually look on your filesystem for the file.
