### ISSUE TITLE
Synth_runner: Pvals & Pvals_std - Calculation 

### ISSUE THREAD

**Issue by kfischery** [bquistorff/synth_runner#28]
First of all, thank you for this great tool and all the effort!

 I need help with the understanding on how synth_runner calculates the Pvals / Pvals_std. Following example: The data includes two treated units (treated on the same year) and eight un-treated units (placebo on the same year).

The results for the first post-treatment year:
Estimates: .0015411 [average treatment-effect of the two treated units]
PVals: .6428571 
Pvals_std: .452381

The Stdv. for the two treated units is 0.003642265 (S) or 0.00257547 (N). 

When I run synth on all untreated units [excl. treated from the data-set] than I get for the eight institutions following averaged results for the same year:

Estimates: .000303053 [average of eight untreated units]

On an individual level I have the following estimates for the same year and unit:

[1] -0.00509145 | [2] 0.0019493 | [3] -0.00446586 | [4] 0.00220556 | [5] 0.00629673 |
[6] -0.00248195 | [7] -0.00384403 | [8] 0.00785612

The Stdv. on these estimates (un-treated units) is equal to 0.004691753 (N) or 0.005015695 (S).

When I calculate it by hand than my results for the Pvals / Pvals_std. are different. How is it calculated? or is there a mistake in the tool?

**Comment by bquistorff** [comment]
Significance testing when there are multiple treated units is  different since we draw pairs of donor differences to construct the placebo distribution. See the help or the Stata Journal article for details. They both reference the Cavallo 2013 paper.
