### ISSUE TITLE
Feature: Return W and V Weight Matricies and Predictor Balance

### ISSUE THREAD

**Issue by aliceolivebrower** [bquistorff/synth_runner#35]
Thank you so much for your work on this package. 

I would like to be able to access the W weight matrix and predictor balance in the ereturn matricies from synth_runner in the same way that you can for synth. I'd also like to be able to see the V weight matrix. Could you add a feature that returns these matricies after the synth_runner command?

**Comment by bquistorff** [comment]
Hi, there can be lots of statistics that one might want to aggregate from the individual runs so it's not easy to provide a simple solution. My thinking was that there wasn't a good solution (see, e.g.,  #8 where I've talked about this before). In thinking about it again, I think the best thing would be to allow the user the input the name of a user-command that `synth_runner` would call after each iteration so the user can check whatever info they want and then save the results to a file indexed by the treated unit's ID. Then after `synth_runner` is done, the user can concatenate these files. 

I'm happy to take pull requests.

**Comment by aliceolivebrower** [comment]
Thanks for the quick response, I'll send a pull request if I'm able to implement your suggestion! In general, accessing the weight matrices from the true treated unit (not the placebos) from the run that generates the synthetic counterfactual would be the most useful.

**Comment by aliceolivebrower** [comment]
Hi again, I haven't yet been able to implement your suggestion, but for the time being, I'm trying to figure out how to get the weight matrix and the predictor balance that synth offers from the true treated unit. I would like to use synth to rerun my main specification (which uses trends and a training period of .5), but I've not been able to figure out from your documentation or code how you define trends in the dependent variable or how you use the first half of the training period to compute the v weights. My plan would be to duplicate your method and manually put a similar trends variable in as a predictor and use a similar method to explicitly specify the v weights. Could you share some of this information?

**Comment by bquistorff** [comment]
For the trends, see [here](https://github.com/bquistorff/synth_runner/blob/a7ea3eef175dc3ed7a593d161cf06cc2188a197d/code/ado/synth_wrapper.ado#L22). For training period, manually specify the predictors to synth (see its `xperiod` option which can help). For eval period, see synth option `mspeperiod`.

**Comment by aliceolivebrower** [comment]
Thanks for pointing me to these resources! From my read of your trends code, it looks like you're replacing the dependent variable with the dependent variable scaled by its value in the last pre-treatment period. Am I reading that correctly? If so, is there a paper on which you based this decision? Looks like there's a lot of ways you could have chosen to define "trend of the dependent variable" and curious why you made that choice.

**Comment by bquistorff** [comment]
Added in b70ff8cd8c.
