### ISSUE TITLE
Panel must be Strongly Balanced

### ISSUE THREAD

**Issue by ranand985** [bquistorff/synth_runner#9]
Hi Brian,

Thank you for writing this package. I was stuck with the "conformability error" while using the 'synth' command. Then I came across your comments on the conformability issues and I downloaded the synth_runner package and made the changes you mentioned.

However, now I am getting the error " Panel must be strongly balanced"
My dataset is weakly balanced and I don't think I can do much about it. Is there any way around this problem?

Thanks,
Rahul

**Comment by bquistorff** [comment]
The best you can do is selectively remove data (either weird units or weird time periods) until it is strongly balanced. Sorry, it's a constraint of the algorithm.
